// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace AndcultureCode.GB.Infrastructure.Data.SqlServer.Migrations
{
    [DbContext(typeof(GBApiContext))]
    partial class GBApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {

        }
    }
}
